### PR TITLE
add support for yosemite

### PR DESCRIPTION
**Pull request by salimane**

### CODE REVIEW

**Comment by salimane** [comment]
any update on this ?
Thanks

**Comment by jverdeyen** [comment]
I can't merge this, I have no permissions..

**Comment by salimane** [comment]
@jverdeyen have you got permissions to merge this now ?

**Comment by jverdeyen** [comment]
No..

**Comment by rafaelfranca** [comment]
Released as 1.4.0

**Comment by rafaelfranca** [comment]
@jverdeyen and now you have access

**Comment by jverdeyen** [comment]
Thx! :+1:

**Pull request merged**
